typography_spectrum: 0.0651339462492615
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#505050'
    - '#828282'
    - '#FF8F08'
  brandStrength: 0.3476139926351607
  lightness: 0.6618943775538355
  saturation: 0.8009221642278135
  rhythmicContrast: 0.7440728538203984
opengraph:
  image: null
  type: 'https://www.facebook.com/mulgagidgee/'
  appId: '470015966470932'
layout_spectrum: 0.42618813714943826
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a299b7f-614d-4999-a8bb-38c28ed7afae.jpg
name: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Values
    id: 0b1c21ed-9371-49cd-87b2-0c39d871e934
    type: content
  - name: Services
    id: 7e4436e7-1bfe-4ace-a1cd-9901efa9b78f
    type: content
  - name: 'Contact '
    id: 39d674ab-7956-4333-bfa1-6fbcbf523b82
    type: content
  - name: About
    id: fce35296-9b68-4211-9705-c27a6742a521
    type: content
favicon: null
title: Mulga Gidgee
description: It's all about relationships
purpose: []
