typography_spectrum: 0.41740448377095163
color:
  brandColors:
    - '#000000'
    - '#ff7d0c'
    - '#ffffff'
    - '#ff0000'
    - '#6f4d16'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: 'https://www.facebook.com/mulgagidgee/'
  appId: '470015966470932'
layout_spectrum: 0.33128
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a299b7f-614d-4999-a8bb-38c28ed7afae.jpg
name: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: Mulga Gidgee
description: It's all about relationships
purpose: []
