typography_spectrum: 0.5214106731582433
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.03249057428911328
  lightness: 0.8653558329679072
  saturation: 0.11052828654646873
  rhythmicContrast: 0.9030247360933572
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9825bcb0-9727-4a44-81c0-a5a276b80cd0.jpg
  type: 'https://www.facebook.com/mulgagidgee/'
  appId: '470015966470932'
layout_spectrum: 0.33128
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
author:
  name: Mulga Gidgee
  email: annie@mulgagidgee.com.au
  url: www.mulgagidgee.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a299b7f-614d-4999-a8bb-38c28ed7afae.jpg
name: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: fce35296-9b68-4211-9705-c27a6742a521
    type: content
  - name: Values
    id: 0b1c21ed-9371-49cd-87b2-0c39d871e934
    type: content
  - name: Services
    id: ba3aa7b5-2b7b-4050-be5b-56fb1bf79e4b
    type: content
  - name: 'Contact '
    id: 39d674ab-7956-4333-bfa1-6fbcbf523b82
    type: content
favicon: null
title: Mulga Gidgee
description: It's all about relationships
purpose: []
