name: Mulga Gidgee
favicon: null
layout_spectrum: 0.33128
typography_spectrum: 0.50147
title: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff7d0c'
    - '#ffffff'
    - '#ff0000'
    - '#6f4d16'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
