typography_spectrum: 0.790873033227399
color:
  brandColors:
    - '#000000'
    - '#FF7D0C'
    - '#FFFFFF'
    - '#FEC35F'
    - '#909090'
  brandStrength: 0.4514942248351872
  lightness: 0.6239269108045846
  saturation: 0.34097528201527894
  rhythmicContrast: 0.9130490317475051
opengraph:
  image: null
  type: 'https://www.facebook.com/mulgagidgee/'
  appId: '470015966470932'
layout_spectrum: 0.8490387594792992
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e9e1040-eb44-4e7b-b20c-ef0a964484cb.png
name: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Values
    id: 0b1c21ed-9371-49cd-87b2-0c39d871e934
    type: content
  - name: About
    id: fce35296-9b68-4211-9705-c27a6742a521
    type: content
  - name: Services
    id: 7e4436e7-1bfe-4ace-a1cd-9901efa9b78f
    type: content
  - name: 'Contact '
    id: 39d674ab-7956-4333-bfa1-6fbcbf523b82
    type: content
favicon: null
title: Mulga Gidgee
description: It's all about relationships
purpose: []
