layout_spectrum: 0.9501493126153946
typography_spectrum: 0.16215287963859737
color:
  brandColors:
    - '#000000'
    - '#FF7700'
    - '#FFFFFF'
    - '#FF0000'
    - '#FFFF00'
  brandStrength: 0.6436708210967481
  lightness: 0.26142887747846544
  saturation: 0.7389387229923159
  rhythmicContrast: 0.11285125580616295
opengraph:
  image: null
  type: 'https://www.facebook.com/mulgagidgee/'
  appId: '470015966470932'
analytics:
  google: UA-72902203-2
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a299b7f-614d-4999-a8bb-38c28ed7afae.jpg
name: Mulga Gidgee
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Values
    id: 0b1c21ed-9371-49cd-87b2-0c39d871e934
    type: content
  - name: 'About '
    id: fce35296-9b68-4211-9705-c27a6742a521
    type: content
  - name: Services
    id: 7e4436e7-1bfe-4ace-a1cd-9901efa9b78f
    type: content
  - name: 'Contact '
    id: 39d674ab-7956-4333-bfa1-6fbcbf523b82
    type: content
favicon: null
title: Mulga Gidgee
description: It's all about relationships
purpose: []
